name: Daily Telegram Send

# Trigger giornaliero + possibilità di trigger manuale
on:
  schedule:
    - cron: '0 10 * * *'   # ogni giorno alle 10:00 UTC (modifica se vuoi altro fuso)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily send script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          DB_FILE: ${{ secrets.DB_FILE }}      # solo se usi SQLite
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # solo se usi PostgreSQL
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python send_daily_script.py
